"""Shared resource limits used at more than one product boundary."""

from __future__ import annotations

DRAG_DROP_FILE_MAX_BYTES = 1024 * 1024 * 1024
DRAG_DROP_AGGREGATE_MAX_BYTES = DRAG_DROP_FILE_MAX_BYTES
MODEL_IMAGE_MAX_BYTES = 5 * 1024 * 1024
INLINE_SCRIPT_MAX_BYTES = 64 * 1024
INLINE_SCRIPT_TOTAL_MAX_BYTES = 256 * 1024
ZIP_CONTAINER_MAX_MEMBERS = 10_000

__all__ = [
    "DRAG_DROP_AGGREGATE_MAX_BYTES",
    "DRAG_DROP_FILE_MAX_BYTES",
    "INLINE_SCRIPT_MAX_BYTES",
    "INLINE_SCRIPT_TOTAL_MAX_BYTES",
    "MODEL_IMAGE_MAX_BYTES",
    "ZIP_CONTAINER_MAX_MEMBERS",
]
